source "https://rubygems.org"

ruby '3.2.0'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'minitest'
gem 'rack-test'

# gem 'webrick'
gem 'rackup', "~> 2.2"
gem 'puma'

# for html rendering
gem 'redcarpet'

gem 'bcrypt' # for password hashing
